# Generated by Django 6.0.3 on 2026-03-08 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('google_places_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('image_url', models.URLField(blank=True)),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.resturant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodRun',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_food_runs', to=settings.AUTH_USER_MODEL)),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_runs', to='api.resturant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
