# Generated by Django 6.0.3 on 2026-03-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resturant_remove_user_username_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='address',
            field=models.CharField(default='1 coetzee street villiersdorp', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resturant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resturant',
            name='phone_number',
            field=models.CharField(default=1111111111, max_length=20),
            preserve_default=False,
        ),
    ]
