# Generated by Django 6.0.3 on 2026-03-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='resturant',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
