# Generated by Django 6.0.3 on 2026-03-09 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_managers_resturant_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrun',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='resturant',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
