# Generated by Django 6.0.3 on 2026-03-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_resturant_to_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='google_places_id',
            field=models.CharField(max_length=128),
        ),
    ]
